### ISSUE TITLE
Following the installation instructions does not work

### ISSUE THREAD

**Issue by Vaccano** [nathanchase/super-minimal-aurelia#4]
I followed the installation instructions and I got the following error when I ran `yarn prod`:

> yarn prod v0.21.3
$ webpack -p --progress --profile --colors
C:\Users\18773\Downloads\super-minimal-aurelia-master\webpack.config.js:8
const { AureliaPlugin } = require("aurelia-webpack-plugin");
...........^ (dots added to get the arrow to line up)

>SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at module.exports (C:\Users\18773\AppData\Roaming\npm\node_modules\webpack\bin\convert-argv.js:80:13)
    at Object.<anonymous> (C:\Users\18773\AppData\Roaming\npm\node_modules\webpack\bin\webpack.js:39:40)
    at Module._compile (module.js:409:26)
error Command failed with exit code 1.

**Comment by nathanchase** [comment]
Try `yarn run prod`. I think `yarn prod` as shorthand only works if you install Yarn via the Windows installer available at https://yarnpkg.com/en/docs/install
